export const currencies = [
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "GBP", symbol: "£", name: "British Pound" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "CAD", symbol: "$", name: "Canadian Dollar" },
  { code: "AUD", symbol: "$", name: "Australian Dollar" },
  { code: "CHF", symbol: "Fr", name: "Swiss Franc" },
  { code: "KRW", symbol: "₩", name: "South Korean Won" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "MXN", symbol: "$", name: "Mexican Peso" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { code: "ZAR", symbol: "R", name: "South African Rand" },
  { code: "SGD", symbol: "$", name: "Singapore Dollar" },
  { code: "HKD", symbol: "$", name: "Hong Kong Dollar" },
  { code: "NZD", symbol: "$", name: "New Zealand Dollar" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { code: "DKK", symbol: "kr", name: "Danish Krone" },
  { code: "PLN", symbol: "zł", name: "Polish Zloty" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { code: "AED", symbol: "د.إ", name: "UAE Dirham" },
  { code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "THB", symbol: "฿", name: "Thai Baht" },
  { code: "VND", symbol: "₫", name: "Vietnamese Dong" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { code: "EGP", symbol: "£", name: "Egyptian Pound" },
  { code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  { code: "AFN", symbol: "؋", name: "Afghan Afghani" },
];
export const timezones = [
  // UTC/GMT
  { value: "UTC", label: "UTC (UTC+00:00)", offset: "UTC+00:00" },
  { value: "GMT", label: "GMT (GMT+00:00)", offset: "GMT+00:00" },

  // Europe
  { value: "Europe/London", label: "London (GMT+00:00)", offset: "GMT+00:00" },
  { value: "Europe/Dublin", label: "Dublin (GMT+00:00)", offset: "GMT+00:00" },
  { value: "Europe/Paris", label: "Paris (CET+01:00)", offset: "CET+01:00" },
  { value: "Europe/Berlin", label: "Berlin (CET+01:00)", offset: "CET+01:00" },
  { value: "Europe/Rome", label: "Rome (CET+01:00)", offset: "CET+01:00" },
  { value: "Europe/Madrid", label: "Madrid (CET+01:00)", offset: "CET+01:00" },
  {
    value: "Europe/Amsterdam",
    label: "Amsterdam (CET+01:00)",
    offset: "CET+01:00",
  },
  {
    value: "Europe/Brussels",
    label: "Brussels (CET+01:00)",
    offset: "CET+01:00",
  },
  { value: "Europe/Zurich", label: "Zurich (CET+01:00)", offset: "CET+01:00" },
  { value: "Europe/Athens", label: "Athens (EET+02:00)", offset: "EET+02:00" },
  {
    value: "Europe/Helsinki",
    label: "Helsinki (EET+02:00)",
    offset: "EET+02:00",
  },
  { value: "Europe/Moscow", label: "Moscow (MSK+03:00)", offset: "MSK+03:00" },
  {
    value: "Europe/Istanbul",
    label: "Istanbul (TRT+03:00)",
    offset: "TRT+03:00",
  },
  { value: "Europe/Kiev", label: "Kiev (EET+02:00)", offset: "EET+02:00" },
  { value: "Europe/Warsaw", label: "Warsaw (CET+01:00)", offset: "CET+01:00" },
  {
    value: "Europe/Stockholm",
    label: "Stockholm (CET+01:00)",
    offset: "CET+01:00",
  },
  { value: "Europe/Oslo", label: "Oslo (CET+01:00)", offset: "CET+01:00" },
  {
    value: "Europe/Copenhagen",
    label: "Copenhagen (CET+01:00)",
    offset: "CET+01:00",
  },
  { value: "Europe/Vienna", label: "Vienna (CET+01:00)", offset: "CET+01:00" },
  { value: "Europe/Prague", label: "Prague (CET+01:00)", offset: "CET+01:00" },
  {
    value: "Europe/Budapest",
    label: "Budapest (CET+01:00)",
    offset: "CET+01:00",
  },

  // Asia
  { value: "Asia/Kabul", label: "Kabul (AFT+04:30)", offset: "AFT+04:30" },
  { value: "Asia/Dubai", label: "Dubai (GST+04:00)", offset: "GST+04:00" },
  { value: "Asia/Karachi", label: "Karachi (PKT+05:00)", offset: "PKT+05:00" },
  { value: "Asia/Kolkata", label: "Kolkata (IST+05:30)", offset: "IST+05:30" },
  { value: "Asia/Colombo", label: "Colombo (IST+05:30)", offset: "IST+05:30" },
  {
    value: "Asia/Kathmandu",
    label: "Kathmandu (NPT+05:45)",
    offset: "NPT+05:45",
  },
  { value: "Asia/Dhaka", label: "Dhaka (BST+06:00)", offset: "BST+06:00" },
  { value: "Asia/Yangon", label: "Yangon (MMT+06:30)", offset: "MMT+06:30" },
  { value: "Asia/Bangkok", label: "Bangkok (ICT+07:00)", offset: "ICT+07:00" },
  { value: "Asia/Jakarta", label: "Jakarta (WIB+07:00)", offset: "WIB+07:00" },
  {
    value: "Asia/Singapore",
    label: "Singapore (SGT+08:00)",
    offset: "SGT+08:00",
  },
  {
    value: "Asia/Hong_Kong",
    label: "Hong Kong (HKT+08:00)",
    offset: "HKT+08:00",
  },
  {
    value: "Asia/Shanghai",
    label: "Shanghai (CST+08:00)",
    offset: "CST+08:00",
  },
  { value: "Asia/Taipei", label: "Taipei (CST+08:00)", offset: "CST+08:00" },
  { value: "Asia/Tokyo", label: "Tokyo (JST+09:00)", offset: "JST+09:00" },
  { value: "Asia/Seoul", label: "Seoul (KST+09:00)", offset: "KST+09:00" },
  { value: "Asia/Manila", label: "Manila (PHT+08:00)", offset: "PHT+08:00" },
  {
    value: "Asia/Kuala_Lumpur",
    label: "Kuala Lumpur (MYT+08:00)",
    offset: "MYT+08:00",
  },
  { value: "Asia/Riyadh", label: "Riyadh (AST+03:00)", offset: "AST+03:00" },
  { value: "Asia/Tehran", label: "Tehran (IRST+03:30)", offset: "IRST+03:30" },
  { value: "Asia/Baghdad", label: "Baghdad (AST+03:00)", offset: "AST+03:00" },
  {
    value: "Asia/Jerusalem",
    label: "Jerusalem (IST+02:00)",
    offset: "IST+02:00",
  },
  { value: "Asia/Beirut", label: "Beirut (EET+02:00)", offset: "EET+02:00" },

  // Australia & Pacific
  {
    value: "Australia/Sydney",
    label: "Sydney (AEDT+11:00)",
    offset: "AEDT+11:00",
  },
  {
    value: "Australia/Melbourne",
    label: "Melbourne (AEDT+11:00)",
    offset: "AEDT+11:00",
  },
  {
    value: "Australia/Brisbane",
    label: "Brisbane (AEST+10:00)",
    offset: "AEST+10:00",
  },
  {
    value: "Australia/Perth",
    label: "Perth (AWST+08:00)",
    offset: "AWST+08:00",
  },
  {
    value: "Australia/Adelaide",
    label: "Adelaide (ACDT+10:30)",
    offset: "ACDT+10:30",
  },
  {
    value: "Australia/Hobart",
    label: "Hobart (AEDT+11:00)",
    offset: "AEDT+11:00",
  },
  {
    value: "Pacific/Auckland",
    label: "Auckland (NZDT+13:00)",
    offset: "NZDT+13:00",
  },
  { value: "Pacific/Fiji", label: "Fiji (FJT+12:00)", offset: "FJT+12:00" },
  { value: "Pacific/Guam", label: "Guam (ChST+10:00)", offset: "ChST+10:00" },

  // North America
  {
    value: "America/New_York",
    label: "New York (EST-05:00)",
    offset: "EST-05:00",
  },
  {
    value: "America/Chicago",
    label: "Chicago (CST-06:00)",
    offset: "CST-06:00",
  },
  { value: "America/Denver", label: "Denver (MST-07:00)", offset: "MST-07:00" },
  {
    value: "America/Phoenix",
    label: "Phoenix (MST-07:00)",
    offset: "MST-07:00",
  },
  {
    value: "America/Los_Angeles",
    label: "Los Angeles (PST-08:00)",
    offset: "PST-08:00",
  },
  {
    value: "America/Anchorage",
    label: "Anchorage (AKST-09:00)",
    offset: "AKST-09:00",
  },
  {
    value: "America/Juneau",
    label: "Juneau (AKST-09:00)",
    offset: "AKST-09:00",
  },
  {
    value: "America/Vancouver",
    label: "Vancouver (PST-08:00)",
    offset: "PST-08:00",
  },
  {
    value: "America/Toronto",
    label: "Toronto (EST-05:00)",
    offset: "EST-05:00",
  },
  {
    value: "America/Mexico_City",
    label: "Mexico City (CST-06:00)",
    offset: "CST-06:00",
  },

  // South America
  {
    value: "America/Sao_Paulo",
    label: "Sao Paulo (BRT-03:00)",
    offset: "BRT-03:00",
  },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "Buenos Aires (ART-03:00)",
    offset: "ART-03:00",
  },
  {
    value: "America/Santiago",
    label: "Santiago (CLT-04:00)",
    offset: "CLT-04:00",
  },
  { value: "America/Lima", label: "Lima (PET-05:00)", offset: "PET-05:00" },
  { value: "America/Bogota", label: "Bogota (COT-05:00)", offset: "COT-05:00" },
  {
    value: "America/Caracas",
    label: "Caracas (VET-04:00)",
    offset: "VET-04:00",
  },
  { value: "America/La_Paz", label: "La Paz (BOT-04:00)", offset: "BOT-04:00" },

  // Africa
  { value: "Africa/Cairo", label: "Cairo (EET+02:00)", offset: "EET+02:00" },
  { value: "Africa/Lagos", label: "Lagos (WAT+01:00)", offset: "WAT+01:00" },
  {
    value: "Africa/Johannesburg",
    label: "Johannesburg (SAST+02:00)",
    offset: "SAST+02:00",
  },
  {
    value: "Africa/Nairobi",
    label: "Nairobi (EAT+03:00)",
    offset: "EAT+03:00",
  },
  {
    value: "Africa/Casablanca",
    label: "Casablanca (WET±00:00)",
    offset: "WET±00:00",
  },
];
export const languages = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "de", name: "German", nativeName: "Deutsch" },
];
