// lib/section-templates-data.ts

export const SECTION_TEMPLATES_DATA = (org: any) => [
  // ============================================
  // NAVBAR
  // ============================================
  {
    name: "Navbar",
    type: "navbar",
    position: 0,
    enabled: false,
    defaultSettings: {
      layout: "default",
      backgroundColor: "#ffffff",
      textColor: "#374151",
      hoverColor: "#f97316",
      activeColor: "#f97316",
      borderBottom: "1px solid #e5e7eb",
      paddingY: 16,
      paddingX: 16,
      maxWidth: "1280px",
      logoSize: "24px",
      logoWeight: 700,
      navLinkSize: "14px",
      navLinkWeight: 500,
      buttonColor: "#f97316",
      buttonHoverColor: "#ea580c",
      buttonTextColor: "#ffffff",
      mobileMenuBg: "#ffffff",
      mobileMenuText: "#374151",
      shadow: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    },
    defaultContent: {
      logo: org?.logo || org?.name || "Your Store",
      logoUrl: org?.logo || "/",
      links: [
        { label: "Home", url: "/" },
        { label: "Products", url: "/products" },
        { label: "Categories", url: "/categories" },
        { label: "About", url: "/about" },
        { label: "Contact", url: "/contact" },
      ],
      buttonText: "Get Started",
      buttonUrl: "/sign-up",
    },
  },

  // ============================================
  // ANNOUNCEMENT BAR
  // ============================================
  {
    name: "Announcement Bar",
    type: "announcement_bar",
    position: 1,
    enabled: false,
    defaultSettings: {
      backgroundColor: "#f97316",
      textColor: "#ffffff",
      hoverColor: "#ffedd5",
      alignment: "center",
      paddingY: 8,
      paddingX: 16,
      fontSize: "14px",
      fontWeight: 500,
      borderBottom: "1px solid #ea580c",
      maxWidth: "1280px",
      linkColor: "#ffffff",
      linkHoverColor: "#ffedd5",
      linkUnderline: true,
    },
    defaultContent: {
      text: "Free shipping on orders over $50!",
      linkText: "Shop Now",
      linkUrl: "/products",
    },
  },

  // ============================================
  // HERO - BOTTOM ALIGNED
  // ============================================
  {
    name: "Hero: Bottom Aligned",
    type: "hero",
    position: 2,
    enabled: false,
    defaultSettings: {
      layout: "bottom-aligned",
      alignment: "center",
      minHeight: "600px",
      backgroundColor: "#ffffff",
      textColor: "#000000",
      paddingY: 80,
      paddingX: 16,
      maxWidth: "1280px",
      titleSize: "48px",
      titleWeight: 700,
      titleColor: "#000000",
      subtitleSize: "24px",
      subtitleColor: "#4b5563",
      buttonPadding: "12px 32px",
      buttonColor: "#f97316",
      buttonHoverColor: "#ea580c",
      buttonTextColor: "#ffffff",
      buttonRadius: "8px",
      buttonFontSize: "16px",
      buttonFontWeight: 500,
      badgeColor: "#ffedd5",
      badgeTextColor: "#ea580c",
      badgePadding: "4px 16px",
      badgeRadius: "9999px",
      badgeFontSize: "14px",
      badgeFontWeight: 500,
      spacing: 24,
      imagePosition: "right",
      imageWidth: "50%",
      contentWidth: "50%",
    },
    defaultContent: {
      title: `Welcome to ${org?.name || "Your Store"}`,
      subtitle:
        org?.description || "Start building your amazing online store today",
      badgeText: "✨ New",
      buttonText: "Shop Now",
      buttonUrl: "/products",
      image: org?.logo || "https://i.ibb.co/MDdmXN3X/IMG-3388.jpg",
    },
  },

  // ============================================
  // HERO - MARQUEE
  // ============================================
  {
    name: "Hero: Marquee",
    type: "hero",
    position: 3,
    enabled: false,
    defaultSettings: {
      layout: "marquee",
      marquee: true,
      alignment: "center",
      minHeight: "500px",
      backgroundColor: "#000000",
      textColor: "#ffffff",
      paddingY: 80,
      paddingX: 16,
      maxWidth: "1280px",
      titleSize: "72px",
      titleWeight: 700,
      titleColor: "#ffffff",
      subtitleSize: "24px",
      subtitleColor: "#d1d5db",
      marqueeSpeed: "20",
      marqueeDuration: "20",
      buttonPadding: "12px 32px",
      buttonColor: "#f97316",
      buttonHoverColor: "#ea580c",
      buttonTextColor: "#ffffff",
      buttonRadius: "8px",
      buttonFontSize: "16px",
      buttonFontWeight: 500,
      badgeColor: "#f97316",
      badgeTextColor: "#ffffff",
      badgePadding: "4px 16px",
      badgeRadius: "9999px",
      badgeFontSize: "14px",
      badgeFontWeight: 500,
      spacing: 24,
    },
    defaultContent: {
      title: `Welcome to ${org?.name || "Your Store"}`,
      subtitle: "Discover amazing products with our scrolling marquee",
      badgeText: "🌟 Trending",
      buttonText: "Explore Now",
      buttonUrl: "/products",
    },
  },

  // ============================================
  // HERO - LARGE LOGO
  // ============================================
  {
    name: "Hero: Large Logo",
    type: "hero",
    position: 4,
    enabled: false,
    defaultSettings: {
      layout: "logo",
      alignment: "center",
      minHeight: "400px",
      backgroundColor: "#ffffff",
      textColor: "#000000",
      paddingY: 80,
      paddingX: 16,
      maxWidth: "896px",
      titleSize: "96px",
      titleWeight: 700,
      titleColor: "#f97316",
      subtitleSize: "24px",
      subtitleColor: "#4b5563",
      spacing: 16,
      logoWidth: "128px",
      logoHeight: "128px",
      logoBg: "#ffedd5",
      logoRadius: "50%",
      logoPadding: 24,
    },
    defaultContent: {
      title: org?.name || "Your Brand Name",
      subtitle: org?.description || "Your tagline goes here",
      logo: org?.logo || "/logo.png",
    },
  },

  // ============================================
  // SLIDESHOW - LAYERED
  // ============================================
  {
    name: "Slideshow: Layered",
    type: "slideshow",
    position: 5,
    enabled: false,
    defaultSettings: {
      layout: "layered",
      minHeight: "600px",
      backgroundColor: "#000000",
      textColor: "#ffffff",
      autoplay: true,
      autoplaySpeed: 5000,
      paddingY: 0,
      paddingX: 0,
      dotsColor: "#f97316",
      dotsInactiveColor: "#9ca3af",
      arrowColor: "rgba(255, 255, 255, 0.2)",
      arrowHoverColor: "rgba(255, 255, 255, 0.4)",
      arrowTextColor: "#ffffff",
      overlayColor: "rgba(0, 0, 0, 0.3)",
      titleSize: "48px",
      titleWeight: 700,
      subtitleSize: "24px",
      buttonColor: "#f97316",
      buttonHoverColor: "#ea580c",
      buttonTextColor: "#ffffff",
      buttonPadding: "12px 32px",
      buttonRadius: "8px",
    },
    defaultContent: {
      title: "Featured Collection",
      slides: [
        {
          image: org?.logo || "/images/slide-1.jpg",
          title: "New Arrivals",
          subtitle: "Discover the latest trends",
        },
        {
          image: "/images/slide-2.jpg",
          title: "Best Sellers",
          subtitle: "Customer favorites",
        },
        {
          image: "/images/slide-3.jpg",
          title: "Special Offer",
          subtitle: "Limited time deals",
        },
      ],
      buttonText: "Shop Collection",
      buttonUrl: "/collections",
    },
  },

  // ============================================
  // SLIDESHOW - FULL FRAME
  // ============================================
  {
    name: "Slideshow: Full Frame",
    type: "slideshow",
    position: 6,
    enabled: false,
    defaultSettings: {
      layout: "full-frame",
      minHeight: "100vh",
      backgroundColor: "#000000",
      textColor: "#ffffff",
      autoplay: true,
      autoplaySpeed: 5000,
      paddingY: 0,
      paddingX: 0,
      dotsColor: "#f97316",
      dotsInactiveColor: "#9ca3af",
      arrowColor: "rgba(255, 255, 255, 0.2)",
      arrowHoverColor: "rgba(255, 255, 255, 0.4)",
      arrowTextColor: "#ffffff",
      overlayColor: "rgba(0, 0, 0, 0.4)",
      titleSize: "72px",
      titleWeight: 700,
      subtitleSize: "30px",
      buttonColor: "#f97316",
      buttonHoverColor: "#ea580c",
      buttonTextColor: "#ffffff",
      buttonPadding: "16px 40px",
      buttonRadius: "8px",
      buttonFontSize: "18px",
    },
    defaultContent: {
      title: "Full Frame Gallery",
      slides: [
        {
          image: org?.logo || "/images/full-1.jpg",
          title: org?.name || "Full Frame 1",
          subtitle: "Immersive experience",
        },
        {
          image: "/images/full-2.jpg",
          title: "Full Frame 2",
          subtitle: "Stunning visuals",
        },
      ],
      buttonText: "Explore",
      buttonUrl: "/gallery",
    },
  },

  // ============================================
  // SLIDESHOW - INSET
  // ============================================
  {
    name: "Slideshow: Inset",
    type: "slideshow",
    position: 7,
    enabled: false,
    defaultSettings: {
      layout: "inset",
      minHeight: "500px",
      backgroundColor: "#ffffff",
      textColor: "#000000",
      autoplay: true,
      autoplaySpeed: 5000,
      paddingY: 32,
      paddingX: 16,
      maxWidth: "1280px",
      dotsColor: "#f97316",
      dotsInactiveColor: "#d1d5db",
      arrowColor: "#ffffff",
      arrowHoverColor: "#fff7ed",
      arrowTextColor: "#f97316",
      overlayColor: "rgba(0, 0, 0, 0.2)",
      titleSize: "48px",
      titleWeight: 700,
      subtitleSize: "20px",
      buttonColor: "#f97316",
      buttonHoverColor: "#ea580c",
      buttonTextColor: "#ffffff",
      buttonPadding: "8px 24px",
      buttonRadius: "8px",
      borderRadius: "12px",
      shadow: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
    },
    defaultContent: {
      title: "Inset Gallery",
      slides: [
        {
          image: org?.logo || "/images/inset-1.jpg",
          title: "Inset 1",
          subtitle: "Elegant display",
        },
        {
          image: "/images/inset-2.jpg",
          title: "Inset 2",
          subtitle: "Sophisticated design",
        },
      ],
      buttonText: "View Gallery",
      buttonUrl: "/gallery",
    },
  },

  // ============================================
  // SPLIT SHOWCASE
  // ============================================
  {
    name: "Split Showcase",
    type: "split",
    position: 8,
    enabled: false,
    defaultSettings: {
      layout: "image-text",
      alignment: "left",
      minHeight: "500px",
      backgroundColor: "#ffffff",
      textColor: "#000000",
      paddingY: 80,
      paddingX: 16,
      maxWidth: "1280px",
      titleSize: "48px",
      titleWeight: 700,
      titleColor: "#000000",
      subtitleSize: "20px",
      subtitleColor: "#4b5563",
      buttonPadding: "12px 32px",
      buttonColor: "#f97316",
      buttonHoverColor: "#ea580c",
      buttonTextColor: "#ffffff",
      buttonRadius: "8px",
      imageWidth: "50%",
      contentWidth: "50%",
      spacing: 24,
      imagePosition: "right",
      imageRadius: "12px",
      shadow: "0 10px 15px -3px rgb(0 0 0 / 0.1)",
      divider: "1px solid #e5e7eb",
    },
    defaultContent: {
      title: "Split Showcase",
      subtitle: "Image on one side, text on the other",
      content:
        org?.description ||
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      image: org?.logo || "/images/split-image.jpg",
      buttonText: "Learn More",
      buttonUrl: "/about",
    },
  },

  // ============================================
  // FEATURED PRODUCTS
  // ============================================
  {
    name: "Featured Products",
    type: "featured_products",
    position: 9,
    enabled: false,
    defaultSettings: {
      layout: "grid",
      columns: 4,
      backgroundColor: "#f9fafb",
      textColor: "#000000",
      paddingY: 80,
      paddingX: 16,
      maxWidth: "1280px",
      titleSize: "36px",
      titleWeight: 700,
      titleColor: "#000000",
      titleAlignment: "center",
      subtitleSize: "16px",
      subtitleColor: "#4b5563",
      showPrices: true,
      showAddToCart: true,
      showQuickView: true,
      productCardBg: "#ffffff",
      productCardRadius: "8px",
      productCardShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
      productCardHoverShadow: "0 20px 25px -5px rgb(0 0 0 / 0.1)",
      productCardPadding: 16,
      productImageHeight: "256px",
      productImageRadius: "8px",
      productNameSize: "14px",
      productNameWeight: 500,
      productNameColor: "#111827",
      productPriceSize: "18px",
      productPriceWeight: 700,
      productPriceColor: "#f97316",
      buttonColor: "#f97316",
      buttonHoverColor: "#ea580c",
      buttonTextColor: "#ffffff",
      buttonWidth: "100%",
      buttonPadding: "8px 0",
      buttonFontSize: "14px",
      buttonRadius: "8px",
      gap: 24,
    },
    defaultContent: {
      title: "Featured Products",
      subtitle: "Discover our handpicked collection",
      products: [],
      buttonText: "View All Products",
      buttonUrl: "/products",
    },
  },

  // ============================================
  // NEWSLETTER SIGNUP
  // ============================================
  {
    name: "Newsletter Signup",
    type: "newsletter",
    position: 11,
    enabled: false,
    defaultSettings: {
      layout: "centered",
      backgroundColor: "#f97316",
      textColor: "#ffffff",
      paddingY: 80,
      paddingX: 16,
      maxWidth: "768px",
      titleSize: "36px",
      titleWeight: 700,
      titleColor: "#ffffff",
      titleAlignment: "center",
      subtitleSize: "18px",
      subtitleColor: "#ffedd5",
      inputBg: "#ffffff",
      inputTextColor: "#111827",
      inputBorder: "none",
      inputRadius: "8px 0 0 8px",
      inputPadding: "12px 16px",
      inputFlex: 1,
      buttonColor: "#000000",
      buttonHoverColor: "#1f2937",
      buttonTextColor: "#ffffff",
      buttonPadding: "12px 32px",
      buttonRadius: "0 8px 8px 0",
      buttonFontSize: "14px",
      buttonFontWeight: 500,
      formLayout: "flex",
      spacing: 24,
      shadow: "0 20px 25px -5px rgb(0 0 0 / 0.1)",
      borderRadius: "8px",
    },
    defaultContent: {
      title: `Subscribe to ${org?.name || "our"} newsletter`,
      subtitle:
        "Get the latest updates and exclusive offers delivered to your inbox",
      buttonText: "Subscribe",
      placeholder: "Enter your email",
      successMessage: "Thank you for subscribing!",
    },
  },

  // ============================================
  // CONTACT FORM
  // ============================================
  {
    name: "Contact Form",
    type: "contact_form",
    position: 12,
    enabled: false,
    defaultSettings: {
      layout: "two-column",
      backgroundColor: "#ffffff",
      textColor: "#000000",
      paddingY: 80,
      paddingX: 16,
      maxWidth: "1024px",
      titleSize: "36px",
      titleWeight: 700,
      titleColor: "#000000",
      titleAlignment: "left",
      subtitleSize: "16px",
      subtitleColor: "#4b5563",
      formBg: "#f9fafb",
      formPadding: 32,
      formRadius: "8px",
      formShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
      inputBg: "#ffffff",
      inputTextColor: "#111827",
      inputBorder: "1px solid #d1d5db",
      inputFocusBorder: "#f97316",
      inputRadius: "8px",
      inputPadding: "12px 16px",
      inputFocusRing: "0 0 0 2px #f97316",
      labelSize: "14px",
      labelWeight: 500,
      labelColor: "#374151",
      buttonColor: "#f97316",
      buttonHoverColor: "#ea580c",
      buttonTextColor: "#ffffff",
      buttonWidth: "100%",
      buttonPadding: "12px 0",
      buttonRadius: "8px",
      buttonFontSize: "14px",
      buttonFontWeight: 500,
      spacing: 16,
    },
    defaultContent: {
      title: "Get in Touch",
      subtitle:
        "We'd love to hear from you. Fill out the form below and we'll get back to you as soon as possible.",
      buttonText: "Send Message",
      fields: [
        {
          type: "text",
          name: "name",
          label: "Your Name",
          placeholder: "John Doe",
        },
        {
          type: "email",
          name: "email",
          label: "Email Address",
          placeholder: "john@example.com",
        },
        {
          type: "textarea",
          name: "message",
          label: "Message",
          placeholder: "Your message here...",
        },
      ],
      successMessage: "Thank you for your message!",
      contactInfo: {
        phone: org?.phone || "+1 (555) 123-4567",
        email: org?.email || "support@yourstore.com",
        address: org?.address || "123 Main St, City, Country",
      },
    },
  },

  // ============================================
  // ABOUT / RICH TEXT
  // ============================================
  {
    name: "About / Rich Text",
    type: "rich_text",
    position: 13,
    enabled: false,
    defaultSettings: {
      alignment: "center",
      backgroundColor: "#ffffff",
      textColor: "#000000",
      paddingY: 80,
      paddingX: 16,
      maxWidth: "896px",
      titleSize: "36px",
      titleWeight: 700,
      titleColor: "#000000",
      titleAlignment: "center",
      contentSize: "18px",
      contentColor: "#374151",
      contentLineHeight: 1.625,
      spacing: 24,
      dividerWidth: "80px",
      dividerColor: "#f97316",
      dividerThickness: "2px",
      dividerMargin: "0 auto",
    },
    defaultContent: {
      title: `About ${org?.name || "Us"}`,
      content: org?.description
        ? `
        <p>${org.description}</p>
      `
        : `
        <p>Welcome to our store! We are passionate about providing the best products and services to our customers.</p>
        <p>Our mission is to deliver quality and value with every purchase. We believe in building long-lasting relationships with our customers through trust and reliability.</p>
        <p>Thank you for choosing us. We look forward to serving you!</p>
      `,
      image: org?.logo || "/images/about-image.jpg",
    },
  },

  // ============================================
  // FAQ
  // ============================================
  {
    name: "FAQ",
    type: "faq",
    position: 14,
    enabled: false,
    defaultSettings: {
      accordion: true,
      backgroundColor: "#f9fafb",
      textColor: "#000000",
      paddingY: 80,
      paddingX: 16,
      maxWidth: "768px",
      titleSize: "36px",
      titleWeight: 700,
      titleColor: "#000000",
      titleAlignment: "center",
      questionSize: "18px",
      questionWeight: 600,
      questionColor: "#111827",
      answerSize: "16px",
      answerColor: "#4b5563",
      faqItemBg: "#ffffff",
      faqItemPadding: 24,
      faqItemRadius: "8px",
      faqItemShadow: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      faqItemHoverShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
      faqItemBorder: "1px solid #e5e7eb",
      faqSpacing: 16,
      iconColor: "#f97316",
      activeBorder: "#f97316",
      divider: "1px solid #e5e7eb",
    },
    defaultContent: {
      title: "Frequently Asked Questions",
      subtitle: "Find answers to common questions",
      faqs: [
        {
          question: "What is your return policy?",
          answer:
            "We accept returns within 30 days of purchase. Items must be in original condition with tags attached.",
        },
        {
          question: "How long does shipping take?",
          answer:
            "Shipping typically takes 3-5 business days. Express shipping options are available at checkout.",
        },
        {
          question: "Do you offer international shipping?",
          answer:
            "Yes, we ship worldwide. International shipping rates and delivery times vary by destination.",
        },
        {
          question: "What payment methods do you accept?",
          answer: "We accept all major credit cards, PayPal, and Apple Pay.",
        },
      ],
    },
  },

  // ============================================
  // TESTIMONIALS
  // ============================================
  {
    name: "Testimonials",
    type: "testimonials",
    position: 15,
    enabled: false,
    defaultSettings: {
      layout: "grid",
      columns: 3,
      backgroundColor: "#ffffff",
      textColor: "#000000",
      paddingY: 80,
      paddingX: 16,
      maxWidth: "1280px",
      titleSize: "36px",
      titleWeight: 700,
      titleColor: "#000000",
      titleAlignment: "center",
      subtitleSize: "16px",
      subtitleColor: "#4b5563",
      cardBg: "#f9fafb",
      cardPadding: 24,
      cardRadius: "8px",
      cardShadow: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      cardHoverShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
      quoteSize: "16px",
      quoteStyle: "italic",
      quoteColor: "#374151",
      authorNameSize: "14px",
      authorNameWeight: 600,
      authorNameColor: "#111827",
      authorRoleSize: "12px",
      authorRoleColor: "#6b7280",
      starColor: "#facc15",
      gap: 24,
      avatarSize: "48px",
      avatarRadius: "50%",
    },
    defaultContent: {
      title: "What Our Customers Say",
      subtitle: "Real reviews from real customers",
      testimonials: [
        {
          id: "t1",
          name: "John Doe",
          role: "Verified Buyer",
          content:
            "Amazing products! The quality exceeded my expectations. Will definitely shop again.",
          rating: 5,
          avatar: org?.logo || "/images/avatar-1.jpg",
        },
        {
          id: "t2",
          name: "Jane Smith",
          role: "Regular Customer",
          content:
            "Excellent customer service and fast shipping. Highly recommend this store to everyone!",
          rating: 5,
          avatar: "/images/avatar-2.jpg",
        },
        {
          id: "t3",
          name: "Mike Johnson",
          role: "First Time Buyer",
          content:
            "Great experience from start to finish. The products are top quality and the prices are reasonable.",
          rating: 4,
          avatar: "/images/avatar-3.jpg",
        },
      ],
    },
  },

  // ============================================
  // FOOTER
  // ============================================
  {
    name: "Footer",
    type: "footer",
    position: 17,
    enabled: false,
    defaultSettings: {
      backgroundColor: "#000000",
      textColor: "#ffffff",
      paddingY: 64,
      paddingX: 16,
      maxWidth: "1280px",
      columns: 4,
      titleSize: "14px",
      titleWeight: 600,
      titleColor: "#ffffff",
      linkSize: "14px",
      linkColor: "#9ca3af",
      linkHoverColor: "#ffffff",
      linkSpacing: 8,
      brandSize: "24px",
      brandWeight: 700,
      brandColor: "#f97316",
      descriptionSize: "14px",
      descriptionColor: "#9ca3af",
      socialIconSize: "20px",
      socialIconColor: "#9ca3af",
      socialIconHoverColor: "#ffffff",
      divider: "1px solid #1f2937",
      copyrightSize: "12px",
      copyrightColor: "#6b7280",
      gap: 32,
      paymentIcons: true,
    },
    defaultContent: {
      brand: org?.name || "Your Store",
      logo: org?.logo || null,
      description:
        org?.description || "Your trusted online store for quality products.",
      links: [
        { label: "About Us", url: "/about" },
        { label: "Contact", url: "/contact" },
        { label: "Privacy Policy", url: "/privacy" },
        { label: "Terms & Conditions", url: "/terms" },
        { label: "Returns", url: "/returns" },
        { label: "FAQ", url: "/faq" },
      ],
      socialLinks: [
        { platform: "Facebook", url: "https://facebook.com", icon: "facebook" },
        { platform: "Twitter", url: "https://twitter.com", icon: "twitter" },
        {
          platform: "Instagram",
          url: "https://instagram.com",
          icon: "instagram",
        },
        { platform: "YouTube", url: "https://youtube.com", icon: "youtube" },
      ],
      copyright: `© 2024 ${org?.name || "Your Store"}. All rights reserved.`,
    },
  },
];
